services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/1_init.sql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3002:3002" # Используем фиксированный порт, так как он совпадает с FRONTEND_PORT
    env_file:
      - ./frontend/.env
      - ./.env
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - PORT=3002 # Явно задаем PORT для react-scripts
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm start

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3003:3003" # Используем фиксированный порт, так как он совпадает с PORT
    env_file:
      - ./backend/.env
      - ./.env
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    command: npm run dev

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    env_file:
      - ./bot/.env
      - ./.env
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./bot:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev

volumes:
  postgres_data: