services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
      - bot
    networks:
      - dev_network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/1_init.sql
    networks:
      - dev_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3002"
    env_file:
      - ./frontend/.env
      - ./env.development-server
    environment:
      - HOST=0.0.0.0
      - PORT=3002
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_HOST=0.0.0.0
      - WDS_SOCKET_PORT=3002
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - dev_network
    command: npm start
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3003:3003"
    env_file:
      - ./backend/.env
      - ./env.development-server
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - dev_network
    command: npm run dev
    restart: unless-stopped

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile.dev
    ports:
      - "3004:3004"
    env_file:
      - ./bot/.env
      - ./env.development-server
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./bot:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - dev_network
    command: npm run dev
    restart: unless-stopped

volumes:
  postgres_data_dev:

networks:
  dev_network:
    driver: bridge 