name: Deploy to Staging

on:
  push:
    branches: [staging]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci
          cd frontend && npm ci
          cd ../backend && npm ci
          cd ../bot && npm ci

      - name: Run tests
        run: |
          cd backend && npm test
          cd ../frontend && npm test -- --watchAll=false

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Build backend
        run: |
          cd backend
          npm run build

  deploy-staging:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Staging Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 89.111.169.243
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🚀 Starting deployment to staging environment..."

            # Переходим в директорию проекта
            cd /var/www/prod

            # Останавливаем текущие контейнеры
            echo "🛑 Stopping current containers..."
            docker-compose -f docker-compose.staging.yml down || true

            # Получаем последние изменения
            echo "📥 Pulling latest changes from staging branch..."
            git fetch origin
            git reset --hard origin/staging

            # Копируем переменные окружения
            echo "🔧 Setting up environment variables..."
            cp env.staging .env.staging || true

            # Собираем и запускаем контейнеры
            echo "🔨 Building and starting containers..."
            docker-compose -f docker-compose.staging.yml build --no-cache
            docker-compose -f docker-compose.staging.yml up -d

            # Ждем запуска сервисов
            echo "⏳ Waiting for services to start..."
            sleep 30

            # Проверяем статус
            echo "🔍 Checking deployment status..."
            docker-compose -f docker-compose.staging.yml ps

            # Проверяем доступность
            echo "🌐 Testing application availability..."
            curl -f https://staging.прибыл.рф/health || echo "Health check failed"

            echo "✅ Staging deployment completed!"
            echo "🌐 Application available at: https://staging.прибыл.рф"

  notify:
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🧪 **Staging Deployment**

            **Status**: ${{ needs.deploy-staging.result == 'success' && '✅ Success' || '❌ Failed' }}
            **Branch**: staging
            **Commit**: ${{ github.sha }}
            **Author**: ${{ github.actor }}

            **URL**: https://staging.прибыл.рф

            ${{ needs.deploy-staging.result == 'success' && '🎉 Deployment successful!' || '⚠️ Deployment failed. Check logs for details.' }}
