name: Deploy to Development

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci
          cd frontend && npm ci
          cd ../backend && npm ci
          cd ../bot && npm ci

      - name: Run tests
        run: |
          cd backend && npm test
          cd ../frontend && npm test -- --watchAll=false

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Build backend
        run: |
          cd backend
          npm run build

  deploy-dev:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Deploy to Development Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 89.111.169.243
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🚀 Starting deployment to development environment..."

            # Переходим в директорию проекта
            cd /var/www/prod

            # Останавливаем текущие контейнеры
            echo "🛑 Stopping current containers..."
            docker-compose -f docker-compose.dev-server.yml down || true

            # Получаем последние изменения
            echo "📥 Pulling latest changes from dev branch..."
            git fetch origin
            git reset --hard origin/dev

            # Копируем переменные окружения
            echo "🔧 Setting up environment variables..."
            cp env.development-server .env.dev || true

            # Собираем и запускаем контейнеры
            echo "🔨 Building and starting containers..."
            docker-compose -f docker-compose.dev-server.yml build --no-cache
            docker-compose -f docker-compose.dev-server.yml up -d

            # Ждем запуска сервисов
            echo "⏳ Waiting for services to start..."
            sleep 30

            # Проверяем статус
            echo "🔍 Checking deployment status..."
            docker-compose -f docker-compose.dev-server.yml ps

            # Проверяем доступность
            echo "🌐 Testing application availability..."
            curl -f http://localhost/health || echo "Health check failed"

            echo "✅ Development deployment completed!"
            echo "🌐 Application available at: https://dev.прибыл.рф"

  notify:
    needs: [deploy-dev]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🚀 **Development Deployment**

            **Status**: ${{ needs.deploy-dev.result == 'success' && '✅ Success' || '❌ Failed' }}
            **Branch**: dev
            **Commit**: ${{ github.sha }}
            **Author**: ${{ github.actor }}

            **URL**: https://dev.прибыл.рф

            ${{ needs.deploy-dev.result == 'success' && '🎉 Deployment successful!' || '⚠️ Deployment failed. Check logs for details.' }}
